//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public string BOMId { get; set; }
        public string BOMRootId { get; set; }
        public string BOMRevision { get; set; }
        public string BOMDescription { get; set; }
        public Nullable<bool> IsActivity { get; set; }
        public Nullable<bool> IsDefaultBOM { get; set; }
        public string DataStatus { get; set; }
        public string FactoryId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] ERPDate { get; set; }
        public string ERPID { get; set; }
    }
}
