//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMItem
    {
        public string BOMItemId { get; set; }
        public string BOMId { get; set; }
        public string ItemSequence { get; set; }
        public string ProductId { get; set; }
        public string SpecificationId { get; set; }
        public Nullable<bool> IsAllowReplace { get; set; }
        public Nullable<bool> IsMESTxn { get; set; }
        public Nullable<bool> IsExpandItem { get; set; }
        public decimal QtyRequired { get; set; }
        public string ItemLocation { get; set; }
        public string ReplaceGroup { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool isReplace { get; set; }
        public string OrgReplaceProd { get; set; }
        public Nullable<bool> IsWHDelivery { get; set; }
        public Nullable<bool> IsStartWorkRM { get; set; }
        public string WorkflowId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsBackFlush { get; set; }
        public Nullable<bool> IsBulk { get; set; }
    }
}
