//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public string FactoryId { get; set; }
        public string FactoryName { get; set; }
        public string FactoryDescription { get; set; }
        public string FactoryAddress { get; set; }
        public string EnterpriseId { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ERPID { get; set; }
    }
}
