//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOProductSpecification
    {
        public string MOProductSpecificationId { get; set; }
        public string MOId { get; set; }
        public string ProductId { get; set; }
        public string SpecificationId { get; set; }
        public Nullable<decimal> StandardWorkingTime { get; set; }
        public string UOMName { get; set; }
        public string WorkcenterShortName { get; set; }
        public string ItemSequence { get; set; }
        public string ERPSequence { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ERPDate { get; set; }
    }
}
