//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrBitMOM_KocelEntities1 : DbContext
    {
        public OrBitMOM_KocelEntities1()
            : base("name=OrBitMOM_KocelEntities1")
        {
        }

        public OrBitMOM_KocelEntities1(string ConnectString)
            : base(ConnectString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MO> MO { get; set; }
        public virtual DbSet<MOItemTask> MOItemTask { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductFamily> ProductFamily { get; set; }
        public virtual DbSet<ProductRoot> ProductRoot { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<Specification_Venture> Specification_Venture { get; set; }
        public virtual DbSet<Venture> Venture { get; set; }
        public virtual DbSet<Venture_Product> Venture_Product { get; set; }
        public virtual DbSet<WorkCenterCalendar> WorkCenterCalendar { get; set; }
        public virtual DbSet<WorkflowStepExpandDefault> WorkflowStepExpandDefault { get; set; }
        public virtual DbSet<BOM> BOM { get; set; }
        public virtual DbSet<BOMItem> BOMItem { get; set; }
        public virtual DbSet<ProductSpecification> ProductSpecification { get; set; }
        public virtual DbSet<SpecificationRoot> SpecificationRoot { get; set; }
        public virtual DbSet<BanChengPinMO> BanChengPinMO { get; set; }
        public virtual DbSet<ChanchengPinMO> ChanchengPinMO { get; set; }
        public virtual DbSet<SysUser> SysUser { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<Shift> Shift { get; set; }
        public virtual DbSet<Venture_Shift> Venture_Shift { get; set; }
        public virtual DbSet<VentureProductFamily> VentureProductFamily { get; set; }
        public virtual DbSet<MOProductSpecification> MOProductSpecification { get; set; }
    }
}
