//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecification
    {
        public string ProductSpecificationId { get; set; }
        public string ProductId { get; set; }
        public string SpecificationId { get; set; }
        public Nullable<int> UPH { get; set; }
        public Nullable<decimal> StandardWorkingTime { get; set; }
        public Nullable<int> WaitTime { get; set; }
        public Nullable<int> ProcessTime { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ERPDATE { get; set; }
        public string SAP_WERKS { get; set; }
        public string SAP_VORNR { get; set; }
        public string SAP_ARBPL { get; set; }
    }
}
