//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFamily
    {
        public string ProductFamilyId { get; set; }
        public string ProductFamilyName { get; set; }
        public string ProductFamilyShortName { get; set; }
        public string ProductFamilyDescription { get; set; }
        public string ParentProductFamilyId { get; set; }
        public string workflowid { get; set; }
        public Nullable<int> SafeStorageTime { get; set; }
        public string ERPNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
