//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRoot
    {
        public string ProductRootId { get; set; }
        public string ProductName { get; set; }
        public string DefaultProductId { get; set; }
        public string ProductFamilyId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
