//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public string SpecificationId { get; set; }
        public string SpecificationRootId { get; set; }
        public string SpecificationRevision { get; set; }
        public string SpecificationDescription { get; set; }
        public Nullable<bool> IsActivity { get; set; }
        public Nullable<bool> IsDefaultSpecification { get; set; }
        public Nullable<bool> IsMetadataFlowStep { get; set; }
        public string WorkflowTypeId { get; set; }
        public string SOPId { get; set; }
        public string DynamicSOP { get; set; }
        public Nullable<int> SOPWidthPercent { get; set; }
        public string MetadataId { get; set; }
        public string DataCollectGroupId { get; set; }
        public string HoldReasonGroupId { get; set; }
        public string LossReasonGroupId { get; set; }
        public string ReworkReasonGroupId { get; set; }
        public string PluginId { get; set; }
        public string MESTxnObjectId { get; set; }
        public string MouldLossReasonGroupId { get; set; }
        public string DataCollectEvent { get; set; }
        public string SkillStatusCode { get; set; }
        public string Sequence { get; set; }
        public string ERPNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string FactoryId { get; set; }
    }
}
