//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venture
    {
        public string VentureId { get; set; }
        public string VentureName { get; set; }
        public string VentureShortName { get; set; }
        public string VentureDescription { get; set; }
        public string Leader { get; set; }
        public string FactoryId { get; set; }
        public string DivisionId { get; set; }
        public string WorkcenterId { get; set; }
        public string HRNo { get; set; }
        public string CostCenterNo { get; set; }
        public string ERPNo { get; set; }
        public string ERPName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
