//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStepExpandDefault
    {
        public string WorkflowStepExpandDefaultId { get; set; }
        public string WorkflowId { get; set; }
        public string WorkflowStepId { get; set; }
        public string WorkflowStepTree { get; set; }
        public string WorkflowStepName { get; set; }
        public string SpecificationId { get; set; }
        public string SubWorkflowId { get; set; }
        public string SubWorkflowStepId { get; set; }
        public string SubWorkflowStepName { get; set; }
        public Nullable<bool> IsMilestone { get; set; }
        public string Sequence { get; set; }
        public string RowNumber { get; set; }
        public string MilestoneRowNumber { get; set; }
    }
}
