//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanSource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCenterCalendar
    {
        public string WorkCenterCalendarID { get; set; }
        public string WorkCenterID { get; set; }
        public Nullable<System.DateTime> NoWorkBeginDate { get; set; }
        public Nullable<System.DateTime> NoWorkEndDate { get; set; }
    }
}
